### ISSUE TITLE
Resource supports no update for Pods and ReplicationControllers

### ISSUE THREAD

**Issue by christianhuening** [qaware/gradle-cloud-deployer#47]
Hi there,

I am trying to deploy into Rancher Kubernetes and receive the following error: 
> de.qaware.cloud.deployer.commons.error.ResourceException: Resource supports no update (Resource: ReplicationController: <myNamespace>/booking-service) (Environment: kub-lab)

Here's my YML:

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    name: my-booking-service
  name: my-booking-service
spec:
  ports:
    - port: 8761
  selector:
    name: booking-service
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: booking-service
  labels:
    name: booking-service
spec:
  containers:
    - image: <validImageName>
      name: booking-service
      ports:
        - containerPort: 8761
          name: booking-service
```
When trying to switch to REPLACE or RESET strategy, I receive a HTTP status code 405 because DELETE seems not to be supported.

So is this an issue with the plugin or more likely with me running kubernetes via rancher?
